// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaApi.Data;

#nullable disable

namespace SpaApi.Migrations
{
    [DbContext(typeof(SpaDbContext))]
    partial class SpaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SpaApi.Domain.BaiViet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("HienThi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HinhAnhUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("MoTaNgan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiDungHtml")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TacGia")
                        .HasColumnType("longtext");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BaiViet", (string)null);
                });

            modelBuilder.Entity("SpaApi.Domain.CaLamViec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("GioBatDau")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("GioKetThuc")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<Guid>("NhanVienId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ThuTrongTuan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId", "ThuTrongTuan");

                    b.ToTable("CaLamViec", (string)null);
                });

            modelBuilder.Entity("SpaApi.Domain.DanhGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DichVuId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LichHenId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DichVuId");

                    b.HasIndex("LichHenId")
                        .IsUnique();

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("SpaApi.Domain.DichVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CapNhatLuc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HienThi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ThoiLuongPhut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ten");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("SpaApi.Domain.DonHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DiaChiGiao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoaiNhan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId", "NgayTao");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("SpaApi.Domain.DonHangChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DonHangId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SanPhamId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("DonHangId", "SanPhamId");

                    b.ToTable("DonHangChiTiet", (string)null);
                });

            modelBuilder.Entity("SpaApi.Domain.KhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("DieuKienToiThieu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HienThi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<decimal?>("PhanTramGiam")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SoTienGiam")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("SpaApi.Domain.LichHen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CapNhatLuc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DichVuId")
                        .HasColumnType("char(36)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("NhanVienId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DichVuId");

                    b.HasIndex("NhanVienId", "ThoiGianBatDau");

                    b.HasIndex("TaiKhoanId", "ThoiGianBatDau");

                    b.ToTable("LichHen", (string)null);
                });

            modelBuilder.Entity("SpaApi.Domain.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CapNhatLuc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("DangLamViec")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("SoDienThoai");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("SpaApi.Domain.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CapNhatLuc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DangBan")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnhUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TonKho")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ten");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("SpaApi.Domain.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CapNhatLuc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SoDienThoai");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("SpaApi.Domain.TrangNoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MaTrang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NoiDungHtml")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MaTrang")
                        .IsUnique();

                    b.ToTable("TrangNoiDung", (string)null);
                });

            modelBuilder.Entity("SpaApi.Domain.CaLamViec", b =>
                {
                    b.HasOne("SpaApi.Domain.NhanVien", "NhanVien")
                        .WithMany("CaLamViecs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SpaApi.Domain.DanhGia", b =>
                {
                    b.HasOne("SpaApi.Domain.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaApi.Domain.LichHen", "LichHen")
                        .WithOne("DanhGia")
                        .HasForeignKey("SpaApi.Domain.DanhGia", "LichHenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaApi.Domain.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("LichHen");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("SpaApi.Domain.DonHang", b =>
                {
                    b.HasOne("SpaApi.Domain.TaiKhoan", "TaiKhoan")
                        .WithMany("DonHangs")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("SpaApi.Domain.DonHangChiTiet", b =>
                {
                    b.HasOne("SpaApi.Domain.DonHang", "DonHang")
                        .WithMany("ChiTiets")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaApi.Domain.SanPham", "SanPham")
                        .WithMany("DonHangChiTiets")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("SpaApi.Domain.LichHen", b =>
                {
                    b.HasOne("SpaApi.Domain.DichVu", "DichVu")
                        .WithMany("LichHens")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaApi.Domain.NhanVien", "NhanVien")
                        .WithMany("LichHens")
                        .HasForeignKey("NhanVienId");

                    b.HasOne("SpaApi.Domain.TaiKhoan", "TaiKhoan")
                        .WithMany("LichHens")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("NhanVien");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("SpaApi.Domain.DichVu", b =>
                {
                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("SpaApi.Domain.DonHang", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("SpaApi.Domain.LichHen", b =>
                {
                    b.Navigation("DanhGia");
                });

            modelBuilder.Entity("SpaApi.Domain.NhanVien", b =>
                {
                    b.Navigation("CaLamViecs");

                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("SpaApi.Domain.SanPham", b =>
                {
                    b.Navigation("DonHangChiTiets");
                });

            modelBuilder.Entity("SpaApi.Domain.TaiKhoan", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("LichHens");
                });
#pragma warning restore 612, 618
        }
    }
}
